version: '3.8'

services:
  fto-service:
    build: .
    container_name: fto-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - weaviate

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-openai
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
